package jhumedadsuelos;
/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../motes/Octopus.h.
 */

public class Constants  {
    public static final byte MODE_AUTO = 1;
    public static final byte SLEEPING = 2;
    public static final byte MX_RATE = 30;
    public static final byte GET_READING_REQUEST = 10;
    public static final byte SCALE_NUM_ALERT = 1;
    public static final byte SET_AWAKE_DUTY_CYCLE_REQUEST = 14;
    public static final byte SET_THRESHOLD_MAX_REQUEST = 4;
    public static final byte SET_THRESHOLD_MIN_REQUEST = 40;
    public static final byte MODE_QUERY = 0;
    public static final byte MASK_MSG_LOGIC = 7;
    public static final short MASK_LAST_LINE = 4096;
    public static final short DEFAULT_SLEEP_DUTY_CYCLE = 2000;
    public static final short DEFAULT_AWAKE_DUTY_CYCLE = 9000;
    public static final short REPLY_MASK = 224;
    public static final short MASK_EPOCH = 4095;
    public static final byte SET_PERIOD_REQUEST = 3;
    public static final short MASK_VERB = 240;
    public static final byte BOOT_REQUEST = 15;
    public static final int MASK_VALUE = 268431360;
    public static final byte SET_MODE_AUTO_REQUEST = 1;
    public static final short AM_OCTOPUS_COLLECTED_MSG = 147;
    public static final short SCALE_VALUE = 4096;
    public static final byte AWAKE = 0;
    public static final byte LOCALISE_REQUEST = 18;
    public static final byte SCALE_SELECT_MSG = 8;
    public static final byte THRESHOLD_REPLY = 96;
    public static final byte SCALE_EPOCH = 1;
    public static final byte CHANNEL_REQUEST = 19;
    public static final byte GET_PERIOD_REQUEST = 8;
    public static final byte MASK_SELECT_MSG = 8;
    public static final byte DEFAULT_THRESHOLD = 0;
    public static final byte PERIOD_REPLY = 64;
    public static final byte AM_OCTOPUS_SENT_MSG = 101;
    public static final byte SET_MODE_QUERY_REQUEST = 2;
    public static final byte SLEEP_MASK = 2;
    public static final short DEFAULT_SAMPLING_PERIOD = 1024;
    public static final byte BROADCAST_DIS_KEY = 42;
    public static final byte MAX_NUM_NODES = 41;
    public static final byte SET_SLEEP_DUTY_CYCLE_REQUEST = 13;
    public static final byte WAIT_TIME = 30;
    public static final byte SLEEP_REQUEST = 6;
    public static final byte SCALE_MSG_LOGIC = 1;
    public static final byte DEFAULT_MODE = 1;
    public static final byte CONDITION_REQUEST = 17;
    public static final short TIMER_CHANGE_CHANNEL = 500;
    public static final short SCALE_LAST_LINE = 4096;
    public static final byte SCALE_VERB = 16;
    public static final short MASK_TYPE = 3840;
    public static final byte AM_OCTOPUS_BROADCAST_MSG = 113;
    public static final short SLEEP_DUTY_CYCLE_REPLY = 128;
    public static final byte NO_REPLY = 0;
    public static final short SCALE_TYPE_READ = 1024;
    public static final byte MAX_ID = 16;
    public static final byte GET_SLEEP_DUTY_CYCLE_REQUEST = 11;
    public static final byte BATTERY_AND_MODE_REPLY = 32;
    public static final short AWAKE_DUTY_CYCLE_REPLY = 160;
    public static final byte GET_THRESHOLD_MAX_REQUEST = 9;
    public static final byte GET_THRESHOLD_MIN_REQUEST = 90;
    public static final byte THRESHOLD_MAX_REPLY = 0x60;
    public static final byte THRESHOLD_MIN_REPLY = 0x61;
    public static final byte WAKE_UP_REQUEST = 7;
    public static final short MASK_NUM_ALERT = 1023;
    public static final short SCALE_TYPE = 256;
    public static final short MINIMUM_SAMPLING_PERIOD = 1024;
    public static final byte MODE_MASK = 1;
    public static final byte GET_AWAKE_DUTY_CYCLE_REQUEST = 12;
    public static final short MASK_TYPE_READ = 7168;
    public static final byte GET_STATUS_REQUEST = 5;
    public static final byte SENSOR_10HS = 127;
    public static final int TOS_BCAST_ADDR=0xFFFF;
    public static final byte READING_REPLY=100;
    public static final long GET_READING_BATTERY_REQUEST=20;
    public static final long READING_BATTERY_REPLY=102;
    public static final long GET_METRIC_REQUEST=21;
    public static final long METRIC_REPLY=103;
    public static final int SET_TIME = 104;
    public static final int SET_TIME_REPLY = 105;
}
